/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { CreateUserTypeArgs } from "./CreateUserTypeArgs";
import { UpdateUserTypeArgs } from "./UpdateUserTypeArgs";
import { DeleteUserTypeArgs } from "./DeleteUserTypeArgs";
import { UserTypeCountArgs } from "./UserTypeCountArgs";
import { UserTypeFindManyArgs } from "./UserTypeFindManyArgs";
import { UserTypeFindUniqueArgs } from "./UserTypeFindUniqueArgs";
import { UserType } from "./UserType";
import { UserFindManyArgs } from "../../user/base/UserFindManyArgs";
import { User } from "../../user/base/User";
import { UserTypeService } from "../userType.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => UserType)
export class UserTypeResolverBase {
  constructor(
    protected readonly service: UserTypeService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "UserType",
    action: "read",
    possession: "any",
  })
  async _userTypesMeta(
    @graphql.Args() args: UserTypeCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [UserType])
  @nestAccessControl.UseRoles({
    resource: "UserType",
    action: "read",
    possession: "any",
  })
  async userTypes(
    @graphql.Args() args: UserTypeFindManyArgs
  ): Promise<UserType[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => UserType, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "UserType",
    action: "read",
    possession: "own",
  })
  async userType(
    @graphql.Args() args: UserTypeFindUniqueArgs
  ): Promise<UserType | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => UserType)
  @nestAccessControl.UseRoles({
    resource: "UserType",
    action: "create",
    possession: "any",
  })
  async createUserType(
    @graphql.Args() args: CreateUserTypeArgs
  ): Promise<UserType> {
    return await this.service.create({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => UserType)
  @nestAccessControl.UseRoles({
    resource: "UserType",
    action: "update",
    possession: "any",
  })
  async updateUserType(
    @graphql.Args() args: UpdateUserTypeArgs
  ): Promise<UserType | null> {
    try {
      return await this.service.update({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => UserType)
  @nestAccessControl.UseRoles({
    resource: "UserType",
    action: "delete",
    possession: "any",
  })
  async deleteUserType(
    @graphql.Args() args: DeleteUserTypeArgs
  ): Promise<UserType | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [User], { name: "users" })
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "read",
    possession: "any",
  })
  async resolveFieldUsers(
    @graphql.Parent() parent: UserType,
    @graphql.Args() args: UserFindManyArgs
  ): Promise<User[]> {
    const results = await this.service.findUsers(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }
}
